import mongoose from 'mongoose';
import dotenv from 'dotenv';
import xlsx from 'xlsx';
import { Student } from './models/studentModel.js';
import Course from './models/courseModel.js';

dotenv.config({ path: 'C:\\Users\\Lalit\\OneDrive\\Desktop\\maya web or backend\\mayacollage\\backend\\.env' });

const EXCEL_DPHARM_2024 = 'c:\\Users\\Lalit\\OneDrive\\Desktop\\maya web or backend\\mayacollage\\webadmin\\mayadata\\D.Pharm 2024-26 C.xlsx';
const EXCEL_DPHARM_2025 = 'c:\\Users\\Lalit\\OneDrive\\Desktop\\maya web or backend\\mayacollage\\webadmin\\mayadata\\D.Pharm 2025-27 C.xlsx';
const EXCEL_MPHARM_2025 = 'c:\\Users\\Lalit\\OneDrive\\Desktop\\maya web or backend\\mayacollage\\webadmin\\mayadata\\M.Pharm 2025-27 C.xlsx';

const updateStudentsFromSheet = async (filePath, courseId, type) => {
    console.log(`Processing file: ${filePath}`);
    const workbook = xlsx.readFile(filePath);
    const sheet = workbook.Sheets[workbook.SheetNames[0]];
    const data = xlsx.utils.sheet_to_json(sheet, { header: 1 });
    
    let updatedCount = 0;
    
    // For M.Pharm, row 0 is headers. For D.Pharm, no headers.
    const startIndex = (type === 'MPHARM') ? 1 : 0;

    for (let i = startIndex; i < data.length; i++) {
        const row = data[i];
        if (!row || row.length === 0 || !row[3]) continue;
        
        const fullName = String(row[3]).trim();
        if (fullName === '' || fullName.toLowerCase().includes('student name')) continue;
        
        const nameParts = fullName.split(' ');
        const firstName = nameParts[0];
        
        let address = '';
        let city = '';
        let state = '';
        let email = '';
        let zipCode = '';

        if (type === 'MPHARM') {
            address = row[4] ? String(row[4]).trim() : '';
            if (row[5]) address += ' ' + String(row[5]).trim();
            state = row[6] ? String(row[6]).trim() : '';
            city = row[7] ? String(row[7]).trim() : '';
            zipCode = row[8] ? String(row[8]).trim() : '';
            email = row[10] ? String(row[10]).trim() : '';
        } else if (type === 'DPHARM') {
            address = row[4] ? String(row[4]).trim() : '';
            state = row[5] ? String(row[5]).trim() : '';
            city = row[6] ? String(row[6]).trim() : '';
            email = row[8] ? String(row[8]).trim() : '';
            // if email contains a gender like MALE/FEMALE because of column shift, skip it
            if (email.toUpperCase() === 'MALE' || email.toUpperCase() === 'FEMALE') {
                email = '';
            }
        }

        // Find the student by first name and course
        // We use regex for case-insensitive and partial match to be safe
        const student = await Student.findOne({
            selectedProgram: courseId,
            firstName: new RegExp('^' + firstName + '$', 'i'),
            // We can also match last name if present, but since we auto-generated 'Student' if missing, let's just find by firstName and check if it's the right one by making sure the generated email matches the previous logic, or just find by father's name or mobile if needed.
            // Actually, we can just find by firstName + lastName combination. Let's do exact fullName check if possible.
        });
        
        if (student) {
            let updated = false;
            if (address && !student.address) { student.address = address; updated = true; }
            if (city && !student.city) { student.city = city; updated = true; }
            if (state && !student.state) { student.state = state; updated = true; }
            if (zipCode && !student.pinCode) { student.pinCode = zipCode; updated = true; }
            
            // Only overwrite email if it's a valid email, not the autogenerated one
            if (email && email.includes('@') && !email.endsWith('mayaerp.com')) { 
                student.email = email.toLowerCase(); 
                updated = true; 
            }
            
            if (updated) {
                await student.save();
                updatedCount++;
            }
        } else {
             // Fallback: Try to find by matching mobile
             const mobile = (type === 'MPHARM') ? (row[9] ? String(row[9]).trim() : null) : (row[7] ? String(row[7]).trim() : null);
             if (mobile) {
                 const studentByMobile = await Student.findOne({ selectedProgram: courseId, mobile: mobile });
                 if (studentByMobile) {
                    let updated = false;
                    if (address && !studentByMobile.address) { studentByMobile.address = address; updated = true; }
                    if (city && !studentByMobile.city) { studentByMobile.city = city; updated = true; }
                    if (state && !studentByMobile.state) { studentByMobile.state = state; updated = true; }
                    if (zipCode && !studentByMobile.pinCode) { studentByMobile.pinCode = zipCode; updated = true; }
                    if (email && email.includes('@') && !email.endsWith('mayaerp.com')) { 
                        studentByMobile.email = email.toLowerCase(); 
                        updated = true; 
                    }
                    if (updated) {
                        await studentByMobile.save();
                        updatedCount++;
                    }
                 }
             }
        }
    }
    
    console.log(`✅ Updated ${updatedCount} students from ${filePath}`);
};

const run = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('📡 Connected to MongoDB');

        const dpharmaCourse = await Course.findOne({ name: 'D.Pharma' });
        const mpharmaCourse = await Course.findOne({ name: { $regex: /M\.?Pharm/i } });

        if (dpharmaCourse) {
            await updateStudentsFromSheet(EXCEL_DPHARM_2024, dpharmaCourse._id, 'DPHARM');
            await updateStudentsFromSheet(EXCEL_DPHARM_2025, dpharmaCourse._id, 'DPHARM');
        }
        
        if (mpharmaCourse) {
            await updateStudentsFromSheet(EXCEL_MPHARM_2025, mpharmaCourse._id, 'MPHARM');
        }

        console.log('🎉 Done updating all missing addresses and emails!');
        process.exit(0);
    } catch (error) {
        console.error('❌ Error:', error);
        process.exit(1);
    }
};

run();
